name: Remyx Recommendation
on:
  workflow_dispatch:
jobs:
  recommend:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: write
      pull-requests: write
      issues: write
    env:
      REMYX_API_KEY: ${{ secrets.REMYX_API_KEY }}
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
    steps:
      - uses: remyxai/remyx-recommendation-action@v1.1.5
        with:
          interest-id: d39347d6-a9b1-4ec2-b4cf-c02103432bab
          rate-limit-days: 0
